[tool.poetry]
name = "pyvpp"
version = "1.0.0"
description = "Python package to download and process vegetation products from WEkEO (HR-VPP) and CDSE (Sentinel-2)"
authors = ["Diego García Díaz <digd.geografo@gmail.com>", "Ricardo Díaz-Delgado <rdiaz@ebd.csic.es>"]
maintainers = ["Diego García Díaz <digd.geografo@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/Digdgeo/PyVPP"
keywords = ["phenology", "hrvpp", "vegetation indexes", "copernicus", "wekeo", "cdse", "sentinel-2", "remote-sensing"]

[tool.poetry.dependencies]
python = ">=3.9, <4.0"
requests = ">=2.28"
geopandas = ">=0.14"
rasterio = ">=1.3"
pyproj = ">=3.4"
shapely = ">=1.8"
deims = ">=3.1"
fiona = ">=1.8.20"
hda = ">=2.18"

[tool.poetry.group.dev.dependencies]
pytest = "^7.2.1"
black = {version = "^23.1.0", optional = true}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.extras]
dev = ["black"]
